---
- name: "Set local variables"
  hosts: localhost
  tasks:
    - name: Generate date-string for today string for next week
      set_fact:
        date_string: "{{ '%Y-%m-%dT%H:%M:%SZ' | strftime( (ansible_date_time.epoch | int )) }}"

    - name: Read from env-variables unless variables passed in to script
      when: not backup_name
      set_fact:
        backup_name: "{{ lookup('env', 'BACKUP_NAME') }}"
        db_vendor: "{{ lookup('env', 'DB_VENDOR') }}"
        db_region: "{{ lookup('env', 'DB_REGION') }}"
        db_name: "{{ lookup('env', 'DB_NAME') }}"
        db_instance_id: "{{ lookup('env', 'DB_INSTANCE_ID') }}"
        db_secret_key: "{{ lookup('env', 'DB_SECRET_KEY') }}"
        object_storage_bucket_name: "{{ lookup('env', 'OBJECT_STORAGE_BUCKET_NAME') }}"
        object_storage_endpoint_url: "{{ lookup('env', 'OBJECT_STORAGE_ENDPOINT_URL') }}"
        object_storage_access_key: "{{ lookup('env', 'OBJECT_STORAGE_ACCESS_KEY') }}"
        object_storage_secret_key: "{{ lookup('env', 'OBJECT_STORAGE_SECRET_KEY') }}"
        object_storage_region: "{{ lookup('env', 'OBJECT_STORAGE_STORAGE_REGION') }}"

    - name: Set backup extension
      set_fact:
        backup_extension_or_default: "{{ backup_extension|default('pgc')}}"

- name: Download remote db
  ansible.builtin.import_playbook: sub-plays/download_scaleway_db.yml
  vars:
    db_region: "{{ db_region }}"
    db_name: "{{ db_name }}"
    db_instance_id: "{{ db_instance_id }}"
    db_secret_key: "{{ db_secret_key }}"
    backup_name: "{{ backup_name }}"
    backup_extension: "{{ backup_extension_or_default }}"
    backup_path: "../../tmp/{{ backup_name }}.{{ backup_extension_or_default }}"

- name: Store to s3
  ansible.builtin.import_playbook: sub-plays/copy_to_s3.yml
  vars:
    source: "../../tmp/{{ backup_name }}.{{ backup_extension_or_default }}"
    destination: "s3://{{ object_storage_bucket_name}}/db-exports/{{ backup_name }}/{{ backup_name }}-{{ date_string }}.{{ backup_extension_or_default }}"

    endpoint_url: "{{ object_storage_endpoint_url }}"
    aws_access_key: "{{ object_storage_access_key }}"
    aws_secret_key: "{{ object_storage_secret_key }}"
    aws_region_name: "{{ object_storage_region }}"
