script:
 - cd ./postgis-sv_se
 - make build
 - cd ../composer-php-7.0
 - make build
 - cd ../composer-php-7.2
 - make build
 - cd ../wp-cli-php-7.2
 - make build
 - cd ../elixir-ubuntu-16-04
 - make build
 - cd ../elixir-ubuntu-18-04
 - make build

after_success:
 - docker login -u $DOCKER_USER -p $DOCKER_PASS
 - cd ./postgis-sv_se
 - make push
 - cd ../wp-cli-php-7.2
 - make push
 - cd ../composer-php-7.0
 - make push
 - cd ../composer-php-7.2
 - make push
 - cd ../elixir-ubuntu-16-04
 - make push
 - cd ../elixir-ubuntu-18-04
 - make push
