script:
 - cd wp-cli-php-7.2 && make build; cd ..
 - cd wp-cli-php-7.4 && make build; cd ..

after_success:
 - docker login -u $DOCKER_USER -p $DOCKER_PASS
 - cd wp-cli-php-7.2 && make push; cd ..
 - cd wp-cli-php-7.4 && make push; cd ..
