name: Publish wp-cli-php
on:
  push:
    branches: [ wp-cli-php ]
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        docker-image:
          - wp-cli-php-8.1
          - wp-cli-php-8.2
          - wp-cli-php-8.3
          - wp-cli-php-8.4
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build ${{ matrix.docker-image }}
        run: make build
        working-directory: ${{ matrix.docker-image }}

      - name: smoke test ${{ matrix.docker-image }}
        run: docker run --rm ghcr.io/frojd/dockerimages/${{ matrix.docker-image }}:latest wp --allow-root --version

      - name: push ${{ matrix.docker-image }}
        run: make push
        working-directory: ${{ matrix.docker-image }}
